// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: log_grpc.proto

package logpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DummyResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DummyResult) Reset() {
	*x = DummyResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DummyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyResult) ProtoMessage() {}

func (x *DummyResult) ProtoReflect() protoreflect.Message {
	mi := &file_log_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyResult.ProtoReflect.Descriptor instead.
func (*DummyResult) Descriptor() ([]byte, []int) {
	return file_log_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *DummyResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DummyResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time      string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Level     string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Msg       string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Category  string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	DebugId   string `protobuf:"bytes,5,opt,name=debug_id,json=debugId,proto3" json:"debug_id,omitempty"`
	Ip        string `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	RequestId string `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Type      string `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Uri       string `protobuf:"bytes,9,opt,name=uri,proto3" json:"uri,omitempty"`
	Id        int32  `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_log_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_log_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Log) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Log) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Log) GetDebugId() string {
	if x != nil {
		return x.DebugId
	}
	return ""
}

func (x *Log) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Log) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Log) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Log) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Log) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SendLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs *Log `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
}

func (x *SendLogsRequest) Reset() {
	*x = SendLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogsRequest) ProtoMessage() {}

func (x *SendLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_log_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogsRequest.ProtoReflect.Descriptor instead.
func (*SendLogsRequest) Descriptor() ([]byte, []int) {
	return file_log_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *SendLogsRequest) GetLogs() *Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_log_grpc_proto protoreflect.FileDescriptor

var file_log_grpc_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x6f, 0x67, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6c, 0x6f, 0x67, 0x67, 0x52, 0x50, 0x43, 0x22, 0x3d, 0x0a, 0x0b, 0x44, 0x75, 0x6d,
	0x6d, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xdd, 0x01, 0x0a, 0x03, 0x4c, 0x6f, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65, 0x62, 0x75,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x62, 0x75,
	0x67, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64,
	0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x6c,
	0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x6f, 0x67, 0x67,
	0x52, 0x50, 0x43, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x32, 0x4c, 0x0a,
	0x0a, 0x4c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x08, 0x53,
	0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x18, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x52, 0x50,
	0x43, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x52, 0x50, 0x43, 0x2e, 0x44, 0x75, 0x6d, 0x6d,
	0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x28, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x6c,
	0x6f, 0x67, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6c, 0x6f, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_log_grpc_proto_rawDescOnce sync.Once
	file_log_grpc_proto_rawDescData = file_log_grpc_proto_rawDesc
)

func file_log_grpc_proto_rawDescGZIP() []byte {
	file_log_grpc_proto_rawDescOnce.Do(func() {
		file_log_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_log_grpc_proto_rawDescData)
	})
	return file_log_grpc_proto_rawDescData
}

var file_log_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_log_grpc_proto_goTypes = []interface{}{
	(*DummyResult)(nil),     // 0: loggRPC.DummyResult
	(*Log)(nil),             // 1: loggRPC.Log
	(*SendLogsRequest)(nil), // 2: loggRPC.SendLogsRequest
}
var file_log_grpc_proto_depIdxs = []int32{
	1, // 0: loggRPC.SendLogsRequest.logs:type_name -> loggRPC.Log
	2, // 1: loggRPC.LogService.SendLogs:input_type -> loggRPC.SendLogsRequest
	0, // 2: loggRPC.LogService.SendLogs:output_type -> loggRPC.DummyResult
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_log_grpc_proto_init() }
func file_log_grpc_proto_init() {
	if File_log_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_log_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DummyResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_log_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_grpc_proto_goTypes,
		DependencyIndexes: file_log_grpc_proto_depIdxs,
		MessageInfos:      file_log_grpc_proto_msgTypes,
	}.Build()
	File_log_grpc_proto = out.File
	file_log_grpc_proto_rawDesc = nil
	file_log_grpc_proto_goTypes = nil
	file_log_grpc_proto_depIdxs = nil
}
